project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - data_cleaning.qmd
    - eda.qmd
    - skill_gap_analysis.qmd
    - ml_methods.qmd
    - career_plan.qmd
    - career_plan2.qmd
    - career_plan3.qmd
    - career_plan4.qmd
website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: data_cleaning.qmd
        text: "Data Preparation"
      - href: eda.qmd
        text: "EDA"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "ML Methods"
      - href: career_plan4.qmd
        text: "Career Strategy"               
          
format:
  html:
    theme: cosmo
    toc: true

execute:
  eval: false

