project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - introduction.qmd
    - data_cleaning.qmd
    - eda.qmd
    - skill_gap_analysis.qmd
    - ml_methods.qmd
    - career_plan.qmd
website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Project Overview"
      - href: data_cleaning.qmd
        text: "Data Preparation"
      - href: eda.qmd
        text: "Exploratory Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "Predictive Modeling"
      - href: career_plan.qmd
        text: "Career Strategy"
format:
  html:
    theme: cosmo
    toc: true

execute:
  eval: false

